#:kivy 2.2.0

<Design>
    BoxLayout:
        orientation:"vertical"
        size: root.width, root.height 

        MDScreen:
            MDLabel:
                adaptive_size: True
                pos_hint: {"center_x": .5, "center_y": .5}
                text: "MDLabel"
                padding: "4dp", "4dp"
                allow_selection: True
                allow_copy: True
                on_copy: print("The text is copied to the clipboard")
