#:kivy 1.9.0

<MyLayout>
    BoxLayout:
        orientation: "vertical"
        size: root.width, root.height
        spacing: 20
        padding: 50

        Button:
            text:"Hello world!"

        Button:
            text: "Goodbye world"

        Button:
            text: "Sup World"
            pos_hint: {'center_x': 0.5}
            size_hint: (1, .2)
            width: 200
            height: 50