#:kivy 2.2.0

<MyLayout>    
    BoxLayout:
        orientation:"vertical"
        size: root.width, root.height

        Label:
            id:slider_label
            text: "Slider"
            font_size: 32
            color: (1, 1, 1)

        Slider:
            min: 0
            max: 100
            step: 1
            orientation: "horizontal"
            on_value: root.slide(*args)
        